# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# old style
format = "\\[${time}\\]-[\\[${username}@${hostname} ${directory}\\]](white) (\\[${git_branch} $git_state(|${git_status})\\]) (${python})\n$battery$character$status "

# Inserts a blank line between shell prompts

add_newline = true

[custom.git_prompt]
disabled = true
# format = '[${git_branch} - ${git_status}]($style) '
when = true
# command = 'echo foo'
# require_repo = true
# command = 'echo foo' # shows output of command
# format = ' transcending [$output]($style)'

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'


[username]
disabled = false
show_always = true
format = '[$user]($style)'
style_user = "bright-red"

[hostname]
disabled = false
ssh_only = false
style = "bright-red"
format = '[$ssh_symbol$hostname]($style)'


[battery]
disabled = false
format = '[$symbol$percentage]($style) '
    [[battery.display]]
    threshold = 25
    style = 'bold red'

    [[battery.display]]
    threshold = 50
    style = 'bold yellow'

    [[battery.display]]
    threshold = 100
    style = 'bold green'

    [package]
    disabled = true




# [env_var]
# disabled = false

[time]
disabled = false
format = '[$time]($style)'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
format = '$symbol'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = ''

[status]
disabled = false
format = '[$status $symbol]($style)'

symbol = '[✗](bold red)'

[git_branch]
# format = 'on [$symbol$branch(:$remote_branch)]($style) ' # default
format = '[$symbol($remote_name/)$branch]($style)' # default
always_show_remote = true



[python]
# format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'


# https://starship.rs/config/#git-status
[git_status]
# all_status = '$conflicted$stashed$deleted$renamed$modified$typechanged$staged$untracked'
format = '([$ahead_behind$all_status]($style))'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
# up_to_date = '✔'
stashed = '[⚑${count}](bold purple)'
conflicted = '[═${count}](bold red)'
deleted = '[✘${count}](bold yellow)'
renamed = '[➜${count}](bold yellow)'
modified = '[✚${count}](bold blue)'
typechanged = '[±${count}]'
staged = '[●${count}](bold yellow)'
untracked = '[…${count}](bold cyan)'
style = 'bright-white'

# format = '$all'
# Which is equivalent to
# format = """
# $username\
# $hostname\
# $localip\
# $shlvl\
# $singularity\
# $kubernetes\
# $directory\
# $vcsh\
# $fossil_branch\
# $fossil_metrics\
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $hg_branch\
# $pijul_channel\
# $docker_context\
# $package\
# $c\
# $cmake\
# $cobol\
# $daml\
# $dart\
# $deno\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $fennel\
# $gleam\
# $golang\
# $guix_shell\
# $haskell\
# $haxe\
# $helm\
# $java\
# $julia\
# $kotlin\
# $gradle\
# $lua\
# $nim\
# $nodejs\
# $ocaml\
# $opa\
# $perl\
# $php\
# $pulumi\
# $purescript\
# $python\
# $quarto\
# $raku\
# $rlang\
# $red\
# $ruby\
# $rust\
# $scala\
# $solidity\
# $swift\
# $terraform\
# $typst\
# $vlang\
# $vagrant\
# $zig\
# $buf\
# $nix_shell\
# $conda\
# $meson\
# $spack\
# $memory_usage\
# $aws\
# $gcloud\
# $openstack\
# $azure\
# $nats\
# $direnv\
# $env_var\
# $mise\
# $crystal\
# $custom\
# $sudo\
# $cmd_duration\
# $line_break\
# $jobs\
# $battery\
# $time\
# $status\
# $os\
# $container\
# $netns\
# $shell\
# $character"""
